version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./logfiles:/var/www/html/logfiles
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./resources:/var/www/html/resources
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./logfiles:/var/www/html/logfiles
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./resources:/var/www/html/resources
